apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-app-backend
spec:
  selector:
    matchLabels:
      app: election-app-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: election-app-backend
    spec:
      containers:
      - name: election-app-postgres
        image: docker.io/abdelhakavaxia/election-app-back-end:dev${DRONE_COMMIT_SHA:0:7}
        imagePullPolicy: Always
        #restart: always
        env: 
        - name: DATABASE_URL
          valueFrom:
                configMapKeyRef:
                      name: back-end-configmap
                      key: DATABASE_URL
        - name: DB_USER
          valueFrom:
                configMapKeyRef:
                      name: back-end-configmap
                      key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
                secretKeyRef:
                      name: back-end-secret
                      key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
                configMapKeyRef:
                      name: back-end-configmap
                      key: DB_HOST
        - name: DB_NAME
          valueFrom:
                configMapKeyRef:
                      name: back-end-configmap
                      key: DB_NAME
        - name: SECRET_KEY
          valueFrom:
                secretKeyRef:
                      name: back-end-secret
                      key: SECRET_KEY
        
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: election-app-backend
spec:
  type: ClusterIP
  selector:
    app: election-app-backend
  ports:
  - name: http
    port: 80
    targetPort: 3001
