apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- back-end-configmap.yaml
- back-end-deploy.yaml
- front-end-configmap.yaml
- front-end-deploy.yaml
- postgres-configmap.yaml
- postgres.yaml
namespace: test
images:
- name: docker.io/abdelhakavaxia/election-app-back-end
  newTag: dev74501a8
- name: docker.io/abdelhakavaxia/election-app-front-end
  newTag: dev${DRONE_COMMIT_BEFORE:0:7}
