apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: postgres
  newName: my-registry/my-postgres
  newTag: v1
- name: nginx
  newTag: 1.8.0
resources:
- test.yaml
#- back-end-configmap.yaml
#- back-end-deploy.yaml
#- front-end-configmap.yaml
#- front-end-deploy.yaml
#- postgres-configmap.yaml
#- postgres.yaml
namespace: test

