apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- back-end-configmap.yaml
- back-end-deploy.yaml
- front-end-configmap.yaml
- front-end-deploy.yaml
- postgres-configmap.yaml
- postgres.yaml
namespace: test

