apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-app-postgres
spec:
  selector:
    matchLabels:
      app: election-app-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: election-app-postgres
    spec:
      containers:
      - name: election-app-postgres
        image: postgres
        env:
          - name: POSTGRES_DB 
            valueFrom:
                configMapKeyRef:
                  name: postgres-configmap 
                  key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_PASSWORD

        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgres/data
          name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: election-app-postgres
spec:
  selector:
    app: election-app-postgres
  ports:
  - name: postgresql
    port: 5432
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume
  labels:
    type: local
    app: election-app-postgres
spec:
  storageClassName: default
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
