apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
  labels: 
    app: election-app
  
spec:
  template:
    spec:
      containers:
      - name: nginxapp
        image: nginx:1.7.9
     
